export type Lang = 'ru' | 'ky';

export const labels: Record<Lang, Record<string, string>> = {
  ru: {
    edit: 'Редактировать',
    saveChanges: 'Сохранить изменения',
    cancel: 'Отмена',
    currency: "Валюта",
    validity: "Срок действия",
    issuance: "Выпуск карты",
    annual_fee: "Годовое обслуживание",
    annual_fee_payroll_first_year: "Первый год (зарплатная карта)",
    annual_fee_payroll_next_years: "Следующие годы (зарплатная карта)",
    payroll_limit: "Лимит по зарплате",
    collateral: "Залог",
    interest_rate_atm_cash: "Процент за снятие в банкомате",
    interest_rate_pos: "Процент за оплату в POS",
    grace_period: "Грейс-период",
    additional_card: "Дополнительная карта",
    card_min_limit: "Минимальный лимит карты",
    limits: "Лимиты",
    contactless: "Бесконтактные операции",
    transactions_count: "Количество операций",
    transactions_amount: "Сумма операций",
    atm_withdraw: "Снятие через банкомат",
    internal_transfer_atm: "Внутренний перевод через банкомат",
    currency_exchange_atm: "Обмен валюты через банкомат",
    pos_non_cash: "Безналичные операции (POS)",
    Services: "Услуги",
    loading: "Загрузка карты...",
    error: "Ошибка при загрузке карты",
    backToList: "Назад к списку",
    cardNotFound: "Карта не найдена",
    description: "Описание",
    notes: "Примечания",
    instructions: "Инструкции",
    rates: "Ставки",
    benefits: "Преимущества",
    conditions: "Условия",
    general: "Общие условия",
    except: "Особые условия",
    name:"Название"
  },
  ky: {
     edit: 'Түзөтүү',
    saveChanges: 'Өзгөртүүлөрдү сактоо',
    cancel: 'Жокко чыгаруу',
    currency: "Валюта",
    validity: "Жарактуулук мөөнөтү",
    issuance: "Карта чыгаруу",
    annual_fee: "Жылдык тейлөө",
    annual_fee_payroll_first_year: "Биринчи жыл (эмгек акылык карта)",
    annual_fee_payroll_next_years: "Кийинки жылдар (эмгек акылык карта)",
    payroll_limit: "Эмгек акылык лимит",
    collateral: "Камсыздоо",
    interest_rate_atm_cash: "Банкоматтан накталай алуу пайызы",
    interest_rate_pos: "POS аркылуу төлөм пайызы",
    grace_period: "Грейс-период",
    additional_card: "Кошумча карта",
    card_min_limit: "Минималдуу лимит",
    limits: "Лимиттер",
    contactless: "Контактсыз операциялар",
    transactions_count: "Операциялардын саны",
    transactions_amount: "Операциялардын суммасы",
    atm_withdraw: "Банкомат аркылуу алуу",
    internal_transfer_atm: "Ички которуу (банкомат)",
    currency_exchange_atm: "Валюта алмашуу (банкомат)",
    pos_non_cash: "Накталай эмес операциялар (POS)",
    Services: "Кызматтар",
    loading: "Карта жүктөлүүдө...",
    error: "Картаны жүктөөдө ката кетти",
    backToList: "Тизмеге кайтуу",
    cardNotFound: "Карта табылган жок",
    description: "Сүрөттөмө",
    notes: "Эскертүүлөр",
    instructions: "Инструкциялар",
    rates: "Ставкалар",
    benefits: "Артыкчылыктар",
    conditions: "Шарттар",
    general: "Жалпы шарттар",
    except: "Өзгөчө шарттар",
    name:"Аты"
  }
};
